#!/usr/bin/env bash
name='linux-firmware'
release='1'
version='20221214'
url='https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git'
description='Firmware files for Linux'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-$version.tar.gz")
depends=()
makedepends=()
md5sums=('SKIP')
group=()
uses=()
dontstrip="31"
arch=('x86_64')

cd $name-$version

package(){
    make install FIRMWAREDIR="/lib/firmware"
}
